dist: trusty

language: php

php:
  - 7.3
  - 7.4
  # - hhvm
  # - nightly

matrix:
  allow_failures:
    # - php: hhvm
    # - php: nightly
  include:
    - php: 7.3
      env:
        - COMPOSER_FLAGS=" --prefer-stable"
        - COVERAGE=true
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer config "platform.ext-mongo" "1.6.16" && composer require alcaeus/mongo-php-adapter; fi

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

before_script:
  - export XDEBUG_MODE=coverage

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
